#!/bin/bash

# File: GMX_replicater
# Description : Build and launch a sequential equilibration and production job in GROMACS
# Version : 1.10
# Last update : 02-09-2025

#######################################################################
##                          GMX_replicater                           ##
#######################################################################
# Script to build and launch a sequential equilibration
# and production job in GROMACS
#
# USAGE:         GMX_replicater [--nodes #nodes] [--nodelist node_name]
#                                                [-c #cores] [-g #gpus]
#                                               [-q queue] [-a account]
#                                                             [options]
#                                                 [--dry] [-h | --help]
#

##  DEFAULT VARIABLES  ################################################

  __version__='1.10'

  nodes_def=1                       # number of nodes (only of SLURM)
  cores_def=16                      # number of cores / parallel enviroment
  memory_def=''                     # RAM memory (100MW = 800MB)
  gpus_def=1                        # number of GPU cards

  queue_def='rasmia_ada'            # name of queue to submit
  account_def='molcat'              # name of account

  msgf=$HOME/msg                    # path for output/error messages
  jobf=$HOME/jobs                   # path to store '.job'
  dry_flg=false                     # dry run: create .job file but do not launch [true, false]
  executable='gmx'                  # executable command
  unload_modules=( 'gromacs')
  load_modules=( 'gromacs/gromacs-2024.3_cuda' )

  topol_def='topol.top'             # topology file

#######################################################################

## Checks if no arguments are in the input
if [ "$1" == "" ]; then
  echo "ERROR: No input arguments. Use -h for help."
  exit
fi

## Checks existence of folders or create them
if [[ ! -d $msgf ]]; then mkdir $msgf; fi
if [[ ! -d $jobf ]]; then mkdir $jobf; fi

## Checks for optional arguments
while [ $# -gt 0 ]; do     # until no more arguments
  arg="$1"
  shift
  case $arg in
    -h|--help)          # print help and exit
      echo "---------------  GMX_replicater  ---------------"
      echo "               GROMACS REPLICATER"
      echo
      echo "Script to build and launch a sequential equilibration and production job in GROMACS."
      echo "At least one .gro, .top and .mdp are needed."
      echo
      echo "Version: $__version__"
      echo
      echo "USAGE:   GMX_replicater [options]"
      echo
      echo "MD OPTIONS:"
      echo " --coord  <.gro>                   coordinates file"
      echo " --topol  <.top>                   topology (def: $topol_def)"
      echo " --equi  <.mdp> ...                equilibration phase (can be multiple, run in order)"
      echo " --prod  <.mdp>                    production phase"
      echo " --index  <.ndx>                   index file"
      echo
      echo "NAMING OPTIONS:"
      echo " --name  <name>                    name for production (def: filename of production's .mdp)"
      echo " -r | --replica  <#> ...           replica number (can be multiple) (naming: '_r#')"
      echo
      echo "COMPUTING OPTIONS:"
      echo " --nodes  <#nodes>                 min number of nodes (def: $nodes_def)"
      echo " --nodelist  <node_name>           name of specific nodes, can be a comma separated list (def: all)"
      echo " -c | --cores  <#cores>            number of cores (def: $cores_def)"
      echo " -g | --gpus  <#gpus>              number of GPUs (def: $gpus_def)"
      echo " -q | --queue  <queue>             queue name (def: $queue_def)"
      echo " -a | --account <account>          account name (def: $account_def)"
      echo " --dry                             dry run: create .job but do not launch"
      echo " -h | --help                       print this help and exit"
      echo
      exit ;;
    --coord)
      coord=$1
      shift ;;
    --topol)
      topol=$1
      shift ;;
    --equi)
      while [ $# -gt 0 ]; do
        if [ ${1:0:1} == "-" ]; then    # break if file starts with '-'
          break
        else
          equi_mdp+=($1)
          shift
        fi
      done ;;
    --prod)
      prod_mdp=$1
      shift ;;
    --index)
      index=$1
      shift ;;
    --name)
      name_over=$1
      shift ;;
    -r|--replica)
      while [ $# -gt 0 ]; do
        if [ ${1:0:1} == "-" ]; then    # break if file starts with '-'
          break
        else
          replica_list+=("_r$1")
          shift
        fi
      done ;;
    --nodes)
      nodes=$1
      shift ;;
    --nodelist)
      nodelist="#SBATCH --nodelist=$1"
      shift
      ;;
    -c|--cores)
      cores=$1
      shift ;;
    -m|--memory)
      memory=$1
      shift ;;
    -g|--gpus)
      gpus=$1
      shift ;;
    -q|--queue)
      queue=$1
      shift
      ;;
    -a|--account)
      account=$1
      shift
      ;;
    --dry)              # dry run
      dry_flg=true
      ;;
    *)                  # error option
      echo "ERROR: Wrong option '$arg'"
      exit ;;
  esac
done

## default values if not specified in input
nodes=${nodes:=$nodes_def}
cores=${cores:=$cores_def}
memory=${memory:=$memory_def}
gpus=${gpus:=$gpus_def}
queue=${queue:=$queue_def}
account=${account:=$account_def}
topol=${topol:=$topol_def}

# check index file
if [ ! -z "$index" ]; then index="-n $index"; fi

# check minimal mandadory options
if [ -z "$prod_mdp" ] || [ -z "$coord" ]; then
  echo "ERROR: coordinates file and production mdp required"
  exit
fi

# check replica number
if [ -z "$replica_list" ]; then
  echo "WARNING: No replica number specified"
  replica_list+=("EMPTY")
fi

## loop over replicas
for replica in ${replica_list[@]}; do
  if [ "$replica" == "EMPTY" ]; then replica=""; fi
  prod_mdp_name=${prod_mdp##*/}; prod_mdp_name=${prod_mdp_name%.*}
  name=${name_over:=${prod_mdp_name}}${replica}    # name of replica

  # check name starts with a digit
  if [[ ${name} =~ ^[0-9] ]]; then
    echo "ERROR: '${name}' name can not start with a digit"
    continue
  fi

  echo "# $name"

  ## write .job file
  jobname="${name}.job"
  printf "#!/bin/bash\n\n" > ${jobname}
  {
    # SLURM -----------------------------------------------------------
    echo "#SBATCH -J ${name}"                    # Job name
    echo "#SBATCH -e $msgf/${name}.msg"          # Error mesages path
    echo "#SBATCH -o $msgf/${name}.msg"          # Output mesages path
    echo "#SBATCH -p ${queue}"                   # Queue name
    echo "#SBATCH -A ${account}"                 # Account name
    echo "#SBATCH -N ${nodes}"                   # Nodes
    echo "#SBATCH --ntasks-per-node=${cores}"    # Cores
    echo "#SBATCH --gpus=${gpus}"                # GPUs
    echo "${nodelist}"                           # List of nodes
    echo ""

    # modules
    for mod in ${unload_modules[@]}; do
      echo "module unload $mod"
    done
    for mod in ${load_modules[@]}; do
      echo "module load $mod"
    done
    echo ""

    unset equi_prev
    crd=$coord

    # equilibration
    if [ ! -z "$equi_mdp" ]; then
      for equi in ${equi_mdp[@]}; do
        equi_name=${equi##*/}; equi_name=${equi_name%.*}${replica}
        printf "$executable grompp -v -p $topol -c $crd -r $crd -f $equi -o ${equi_name}.tpr $index"
        # use checkpoint if not the first run
        if [ ! -z "$equi_prev" ]; then
          printf " -t ${equi_prev}.cpt"
        fi
        printf "\n$executable mdrun -nt $(($nodes * $cores)) -s ${equi_name}.tpr -deffnm ${equi_name} \n\n"
        crd=${equi_name}.gro
        equi_prev=${equi_name}
      done
    else
      echo "WARNING: No equilibration specified. Skipping this step." >&2
    fi

    # production
    printf "$executable grompp -v -p $topol -c $crd -r $crd -f $prod_mdp -o ${name}.tpr $index"
    # use checkpoint if not the first run
    if [ ! -z "$equi_prev" ]; then
      printf " -t ${equi_prev}.cpt"
    fi
    printf "\n$executable mdrun -nt $(($nodes * $cores)) -s ${name}.tpr -deffnm ${name} \n"
  } >> ${jobname}

  ## launch
  if [ "$dry_flg" == "true" ]; then
    echo "Job file '${jobname}' succesfully created!"
  else
    sbatch ${jobname}
    mv ${jobname} $jobf  # move .job file to proper folder
  fi
done
