#!/bin/bash

# File: ORCA_launcher
# Description : ORCA job launcher
# Version : 1.3
# Last update : 31-03-2022

#######################################################################
##                           ORCA_launcher                           ##
#######################################################################
# Launcher for multiple jobs at a time and set computational variables
#
# USAGE:              ORCA_launcher [-c #cores] [-m #memory] [-q queue]
#                                                 [--dry] [-h | --help]
#                                         <file1.inp> <file2.inp> <...>
#
# all the '-*' arguments must preceed the input files
# [*] options are optional, <*> files are mandatory
#

##  DEFAULT VARIABLES  ################################################

  __version__='1.3'

  nodes_def=1                       # number of nodes (only of SLURM)
  cores_def=8                       # number of cores / parallel enviroment
  memory_def='4000MB'               # RAM memory (100MW = 800MB)

  queue_sge='BIFIZCAM'              # name of queue to submit
  queue_slurm='bifi'                # name of queue to submit

  origin=$PWD                       # path of the input files
  destination=$PWD                  # path to store the outputs
  msgf=$HOME/msg                    # path for output/error messages
  jobf=$HOME/jobs                   # path to store '.job'
  dry_flg=false                     # dry run: create .job file but do not launch [true, false]
  allowed_exten=( 'inp' )           # allowed file extensions
  executable='/cm/shared/apps/orca/4.0.1.2/orca'
  modules=( 'openmpi/gcc/64/2.1.1' 'orca/4.0.1.2' )

#######################################################################

## Checks if no arguments are in the input
if [ "$1" == "" ]; then
  echo "ERROR: No input arguments. Use -h for help."
  exit
fi

## Checks existence of folders or create them
if [[ ! -d $msgf ]]; then mkdir $msgf; fi
if [[ ! -d $jobf ]]; then mkdir $jobf; fi

## Checks for optional arguments
while [ ${1:0:1} == "-" ]; do     # until arguments does not start with '-'
  arg="$1"
  shift
  case $arg in
    -h|--help)          # print help and exit
      echo "---------------  ORCA_launcher  ---------------"
      echo "                 ORCA LAUNCHER"
      echo
      echo "Version: $__version__"
      echo
      echo "USAGE:   ORCA_launcher [options] <file.inp> ..."
      echo
      echo "OPTIONS:"
      echo " --nodes  <#nodes>                 number of nodes (def: $nodes_def)"
      echo " -c | --cores  <#cores>            number of cores (def: $cores_def)"
      echo " -m | --memory  <memory>           amount of RAM memory (def: $memory_def)"
      echo " -q | --queue  <queue>             queue name (SGE: $queue_sge / SLURM: $queue_slurm)"
      echo " --dry                             dry run: create .job but do not launch"
      echo " -h | --help                       print this help and exit"
      echo
      echo "INPUT:"
      echo " <file.inp> ...                    orca input file"
      echo "                                   must be the last argument, can me multiple"
      exit ;;
    --nodes)
      nodes=$1
      shift
      ;;
    -c|--cores)
      cores_in=$1
      cores_flg=true
      shift
      ;;
    -m|--memory)
      memory_in=$1
      memory_flg=true
      shift
      ;;
    -q|--queue)
      queue_sge=$1
      queue_slurm=$1
      shift
      ;;
    --dry)              # dry run
      dry_flg=true
      ;;
    *)                  # error option
      echo "ERROR: Wrong option '$arg'"
      exit ;;
  esac
done

## default values if not specified in input
nodes=${nodes:=$nodes_def}
cores_in=${cores_in:=$cores_def}
memory_in=${memory_in:=$memory_def}

## go through every input file found in the arguments
for file in "$@"; do

  name=${file%.*}       # name of input file without extension
  exten=${file##*.}     # extension of input file

  # initializate values
  cores=$cores_in
  memory=$memory_in

  # check file existence, if starts with a digit and extension
  if [ ! -f $file ]; then
    echo "ERROR: '$file' not found"
    continue
  elif [[ ${name} =~ ^[0-9] ]]; then
    echo "ERROR: '${file}' name can not start with a digit"
    continue
  elif [[ ! ${allowed_exten[*]} =~ $(echo "\<${exten}\>") ]]; then
	  echo "ERROR: '$file' is not a valid input file (wrong extension)"
    continue
  fi

  # convert to UNIX format (prevent line-ending errors)
  { dos2unix -q -k $file ; } 2>/dev/null

  ## computational parameters
  #TODO: automatic handling of PAL# and %maxcore

  ## write .job file
  jobname="${name}.job"
  printf "#!/bin/bash\n\n" > ${jobname}
  {
    # SGE -------------------------------------------------------------
    echo "#$ -N ${name}"                         # Job name
    echo "#$ -e $msgf/${name}.msg"               # Error mesages path
    echo "#$ -o $msgf/${name}.msg"               # Output mesages path
    echo "#$ -q $queue_sge"                      # Queue name
    echo "#$ -R yes"                             # Reservation enabled
    echo "#$ -cwd"                               # Run in current working directory
    if [ "$cores" != '1' ]; then
      echo "#$ -pe mp$cores $cores"              # Parallel environment (cores)
    fi
    echo ""
    # SLURM -----------------------------------------------------------
    echo "#SBATCH -J ${name}"                    # Job name
    echo "#SBATCH -e $msgf/${name}.msg"          # Error mesages path
    echo "#SBATCH -o $msgf/${name}.msg"          # Output mesages path
    echo "#SBATCH -p ${queue_slurm}"             # Queue name
    echo "#SBATCH -N ${nodes}"                   # nodes
    echo "#SBATCH --ntasks-per-node=${cores}"    # cores
    echo "#SBATCH --mem=${memory}"               # memory
    echo ""

    # modules
    for mod in ${modules[@]}; do
      echo "module load $mod"
    done

    printf "\ncd $origin \n\n"

    # main execution
    echo "${executable} $origin/$file > $destination/${name}.out"
  } >> ${jobname}

  ## launch
  if [ "$dry_flg" == "true" ]; then
    echo "Job file '${jobname}' succesfully created!"
  else
    { qsub ${origin}/${jobname} ; } 2>/dev/null
    { sbatch ${origin}/${jobname} ; } 2>/dev/null
    mv ${origin}/${jobname} $jobf  # move .job file to proper folder
  fi
done
