#!/bin/bash

# File: ORCA_launcher
# Description : ORCA job launcher
# Version : 1.6
# Last update : 23-05-2024

#######################################################################
##                           ORCA_launcher                           ##
#######################################################################
# Launcher for multiple jobs at a time and set computational variables
#
# USAGE:        ORCA_launcher [--nodes #nodes] [-c #cores] [-m #memory]
#                                       [-q queue] [-a account] [--dir]
#                                                 [--dry] [-h | --help]
#                                         <file1.inp> <file2.inp> <...>
#
# all the '-*' arguments must preceed the input files
# [*] options are optional, <*> files are mandatory
#

##  DEFAULT VARIABLES  ################################################

  __version__='1.6'

  nodes_def=1                       # min number of nodes
  cores_def=8                       # number of cores / parallel enviroment
  memory_def='16GB'                 # RAM memory (100MW = 800MB)

  queue_def='thin'                  # name of queue to submit
  account_def='molcat'              # name of account

  msgf=$HOME/msg                    # path for output/error messages
  jobf=$HOME/jobs                   # path to store '.job'
  dry_flg=false                     # dry run: create .job file but do not launch [true, false]
  dir_flg=false                     # create a directory for the calculation to be lauch there [true, false]
  allowed_exten=( 'inp' )           # allowed file extensions
  executable='orca'
  modules=( 'orca/5.0.4' )

#######################################################################

## Checks if no arguments are in the input
if [ "$1" == "" ]; then
  echo "ERROR: No input arguments. Use -h for help."
  exit
fi

## Checks existence of folders or create them
if [[ ! -d $msgf ]]; then mkdir $msgf; fi
if [[ ! -d $jobf ]]; then mkdir $jobf; fi

## Checks for optional arguments
while [ ${1:0:1} == "-" ]; do     # until arguments does not start with '-'
  arg="$1"
  shift
  case $arg in
    -h|--help)          # print help and exit
      echo "---------------  ORCA_launcher  ---------------"
      echo "                 ORCA LAUNCHER"
      echo
      echo "Version: $__version__"
      echo
      echo "USAGE:   ORCA_launcher [options] <file.inp> ..."
      echo
      echo "OPTIONS:"
      echo " --nodes  <#nodes>                 min number of nodes (def: $nodes_def)"
      echo " -c | --cores  <#cores>            number of cores (def: $cores_def)"
      echo " -m | --memory  <memory>           amount of RAM memory (def: $memory_def)"
      echo " -q | --queue  <queue>             queue name (def: $queue)"
      echo " -a | --account <account>          account name (def: $account_def)"
      echo " --dir                             create a directory for the calculation and lauch there"
      echo " --dry                             dry run: create .job but do not launch"
      echo " -h | --help                       print this help and exit"
      echo
      echo "INPUT:"
      echo " <file.inp> ...                    orca input file"
      echo "                                   must be the last argument, can me multiple"
      exit ;;
    --nodes)
      nodes=$1
      shift
      ;;
    -c|--cores)
      cores_in=$1
      cores_flg=true
      shift
      ;;
    -m|--memory)
      memory_in=$1
      memory_flg=true
      shift
      ;;
    -q|--queue)
      queue_def=$1
      shift
      ;;
    -a|--account)
      account=$1
      shift
      ;;
    --dir)              # create directory
      dir_flg=true
      ;;
    --dry)              # dry run
      dry_flg=true
      ;;
    *)                  # error option
      echo "ERROR: Wrong option '$arg'"
      exit ;;
  esac
done

## default values if not specified in input
nodes=${nodes:=$nodes_def}
cores_in=${cores_in:=$cores_def}
memory_in=${memory_in:=$memory_def}
queue=${queue:=$queue_def}
account=${account:=$account_def}

## go through every input file found in the arguments
for file in "$@"; do

  name=${file%.*}       # name of input file without extension
  exten=${file##*.}     # extension of input file

  # initializate values
  cores=$cores_in
  memory=$memory_in

  # check file existence, if starts with a digit and extension
  if [ ! -f $file ]; then
    echo "ERROR: '$file' not found"
    continue
  elif [[ ${name} =~ ^[0-9] ]]; then
    echo "ERROR: '${file}' name can not start with a digit"
    continue
  elif [[ ! ${allowed_exten[*]} =~ $(echo "\<${exten}\>") ]]; then
	  echo "ERROR: '$file' is not a valid input file (wrong extension)"
    continue
  fi

  # convert to UNIX format (prevent line-ending errors)
  { dos2unix -q -k $file ; } 2>/dev/null

  ## computational parameters
  #TODO: automatic handling of PAL# and %maxcore

  # create calculation directory if requested
  if [ $dir_flg == "true" ]; then
    mkdir -p $name
    mv $file $name/
    cd $name
  fi

  ## write .job file
  jobname="${name}.job"
  printf "#!/bin/bash\n\n" > ${jobname}
  {
    # SLURM -----------------------------------------------------------
    echo "#SBATCH -J ${name}"                    # Job name
    echo "#SBATCH -e $msgf/${name}.msg"          # Error mesages path
    echo "#SBATCH -o $msgf/${name}.msg"          # Output mesages path
    echo "#SBATCH -p ${queue}"                   # Queue name
    echo "#SBATCH -A ${account}"                 # Account name
    echo "#SBATCH -N ${nodes}"                   # Nodes
    echo "#SBATCH -c ${cores}"                   # Cores
    echo "#SBATCH --mem=${memory}"               # Memory
    echo ""

    # modules
    for mod in ${modules[@]}; do
      echo "module load $mod"
    done

    # main execution
    echo "executable=\$(which ${executable})"
    echo "\${executable} $file > ${name}.out"
  } >> ${jobname}

  ## launch
  if [ "$dry_flg" == "true" ]; then
    echo "Job file '${jobname}' succesfully created!"
  else
    sbatch ${jobname}
    mv ${jobname} $jobf  # move .job file to proper folder
  fi

  # return to original directory
  if [ $dir_flg == "true" ]; then
    cd ..
  fi

done
